kind: Namespace
apiVersion: v1
metadata:
  name: installer
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: installer
  namespace: installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: installer
  namespace: installer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: installer
  name: installer
  namespace: installer
spec:
  containers:
  - image: quay.io/failk8s/test
    name: installer
    command:
      - "/home/kubeuser/install"
      - "dev"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  serviceAccountName: installer
