apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tanzu-challenge-developer
spec:
  title: Developer edition
  description: Customer empathy challenge - Developer edition
  url: https://github.com/eduk8s-tests/lab-tanzu-challenge
  content:
    files: github.com/eduk8s-tests/lab-tanzu-challenge
  session:
    namespaces:
      budget: x-small
    applications:
      terminal:
        enabled: true
      registry:
        enabled: true
    dashboards:
    - name: Survey
      url: https://docs.google.com/forms/d/e/1FAIpQLScPK90aFENQgnC3hEBuo_kvdy3l1VkhvA8nc8QhNlKCBd9RLA/viewform?embedded=true
    env:
    - name: WORKSHOP_FILE
      value: workshop-developer.yaml
    - name: EXERCISES_DIR
      value: exercises/developer
---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tanzu-challenge-devops
spec:
  title: DevOps edition
  description: Customer empathy challenge - DevOps edition
  url: https://github.com/eduk8s-tests/lab-tanzu-challenge
  content:
    files: github.com/eduk8s-tests/lab-tanzu-challenge
  session:
    namespaces:
      budget: x-small
    applications:
      terminal:
        enabled: true
      registry:
        enabled: true
    dashboards:
    - name: Survey
      url: https://docs.google.com/forms/d/e/1FAIpQLScPK90aFENQgnC3hEBuo_kvdy3l1VkhvA8nc8QhNlKCBd9RLA/viewform?embedded=true
    env:
    - name: WORKSHOP_FILE
      value: workshop-devops.yaml
    - name: EXERCISES_DIR
      value: exercises/developer
---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tanzu-challenge-operations
spec:
  title: Operations edition
  description:  Customer empathy challenge - Operations edition
  url: https://github.com/eduk8s-tests/lab-tanzu-challenge
  content:
    files: github.com/eduk8s-tests/lab-tanzu-challenge
  session:
    namespaces:
      budget: x-small
    applications:
      terminal:
        enabled: false
      registry:
        enabled: true
    dashboards:
    - name: Survey
      url: https://docs.google.com/forms/d/e/1FAIpQLScPK90aFENQgnC3hEBuo_kvdy3l1VkhvA8nc8QhNlKCBd9RLA/viewform?embedded=true
    env:
    - name: WORKSHOP_FILE
      value: workshop-operations.yaml
---